=encoding utf-8

=head1 NAME

At - The AT Protocol for Social Networking

=head1 SYNOPSIS

    use At;
    my $at = At->new( host => 'https://fun.example' );
    $at->createSession( 'sanko', '1111-aaaa-zzzz-0000' );
    $at->createRecord(
        collection => 'app.bsky.feed.post',
        record     => { '$type' => 'app.bsky.feed.post', text => 'Hello world! I posted this via the API.', createdAt => time }
    );

=head1 DESCRIPTION

The AT Protocol is a "social networking technology created to power the next generation of social applications."

At.pm uses perl's new class system which requires perl 5.38.x or better and, like the protocol itself, is still under
development.

=head2 At::Bluesky

At::Bluesky is a subclass with the host set to C<https://bluesky.social> and all the lexicon related to the social
networking site included.

=head2 App Passwords

Taken from the AT Protocol's official documentation:

=for html <blockquote>

For the security of your account, when using any third-party clients, please generate an L<app
password|https://atproto.com/specs/xrpc#app-passwords> at Settings > Advanced > App passwords.

App passwords have most of the same abilities as the user's account password, but they're restricted from destructive
actions such as account deletion or account migration. They are also restricted from creating additional app passwords.

=for html </blockquote>

Read their disclaimer here: L<https://atproto.com/community/projects#disclaimer>.

=head1 Methods

Honestly, to keep to the layout of the underlying protocol, almost everything is handled in members of this class.

=head2 C<new( ... )>

Creates an AT client and initiates an authentication session.

    my $self = At->new( host => 'https://bsky.social' );

Expected parameters include:

=over

=item C<host> - required

Host for the account. If you're using the 'official' Bluesky, this would be 'https://bsky.social' but you'll probably
want C<At::Bluesky-E<gt>new(...)> because that client comes with all the bits that aren't part of the core protocol.

=back

=head2 C<disableAccountInvites( ... )>

Disable an account from receiving new invite codes, but does not invalidate existing codes.

Expected parameters include:

=over

=item C<account> - required

DID of account to modify.

=item C<note>

Optional reason for disabled invites.

=back

=head2 C<disableInviteCodes( )>

Disable some set of codes and/or all codes associated with a set of users.

Expected parameters include:

=over

=item C<codes>

List of codes.

=item C<accounts>

List of account DIDs.

=back

=head1 Sync Methods

Keeping a mirror in sync is easy with these methods.

=head2 C<getBlocks( ... )>

    $at->getBlocks( 'did...' );

Get blocks from a given repo.

Expected parameters include

=over

=item C<did> - required

The DID of the repo.

=item C<cids> - required

=back

=head2 C<getLatestCommit( ... )>

    $at->getLatestCommit( 'did...' );

Get the current commit CID & revision of the repo.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=back

Returns the revision and cid on success.

=head2 C<getRecord( ..., [...] )>

    $at->getRecord( 'did...', ... );

Get blocks needed for existence or non-existence of record.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=item C<collection> - required

NSID.

=item C<rkey> - required

=item C<commit>

An optional past commit CID.

=back

=head2 C<getRepo( ... )>

    $at->getRepo( 'did...', ... );

Gets the DID's repo, optionally catching up from a specific revision.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=item C<since>

The revision of the repo to catch up from.

=back

=head2 C<listBlobs( ..., [...] )>

    $at->listBlobs( 'did...' );

List blob CIDs since some revision.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=item C<since>

on of the repo to list blobs since.

=item C<limit>

Minimum is 1, maximum is 1000, default is 500.

=item C<cursor>

=back

On success, a list of cids is returned and, optionally, a cursor.

=head2 C<listRepos( [...] )>

    $at->listRepos( );

List DIDs and root CIDs of hosted repos.

Expected parameters include:

=over

=item C<limit>

Maximum is 1000, minimum is 1, default is 500.

=item C<cursor>

=back

On success, a list of C<At::Lexicon::com::atproto::sync::repo> objects is returned and, optionally, a cursor.

=head2 C<notifyOfUpdate( ... )>

    $at->notifyOfUpdate( 'example.com' );

Notify a crawling service of a recent update; often when a long break between updates causes the connection with the
crawling service to break.

Expected parameters include:

=over

=item C<hostname> - required

Hostname of the service that is notifying of update.

=back

Returns a true value on success.

=head2 C<requestCrawl( ... )>

    $at->requestCrawl( 'example.com' );

Request a service to persistently crawl hosted repos.

Expected parameters include:

=over

=item C<hostname> - required

Hostname of the service that is requesting to be crawled.

=back

Returns a true value on success.

=head2 C<getBlob( ... )>

    $at->getBlob( 'did...', ... );

Get a blob associated with a given repo.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=item C<cid> - required

The CID of the blob to fetch.

=back

=begin TODO

=head2 C<subscribeRepos( ... )>

    $at->subscribeRepos( sub {...} );

Subscribe to repo updates.

Expected parameters include:

=over

=item C<cb> - required

=item C<cursor>

The last known event to backfill from.

=back

=head2 C<subscribeRepos_p( ... )>


=end TODO

=head1 Temp Methods

These are methods the At Protocol has not placed in a proper namespace. They might be incomplete or depreciated.
Regardless, they are placed in a lexicon named C<com.atproto.temp.*>.

=head2 C<fetchLabels( [...] )>

    $at->fetchLabels;

Fetch all labels from a labeler created after a certain date.

Expected parameters include:

=over

=item C<since>

=item C<limit>

Default is 50, minimum is 1, maximum is 250.

=back

Returns a list of labels as new C<At::Lexicon::com::atproto::label> objects on success.

=head2 C<pushBlob( ... )>

    $at->pushBlob( 'did:...' );

Gets the did's repo, optionally catching up from a specific revision.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=back

=head2 C<transferAccount( ... )>

    $at->transferAccount( ... );

Transfer an account.

Expected parameters include:

=over

=item C<handle> - required

=item C<did> - required

=item C<plcOp> - required

=back

=head2 C<importRepo( ... )>

    $at->importRepo( 'did...' );

Gets the did's repo, optionally catching up from a specific revision.

Expected parameters include:

=over

=item C<did> - required

The DID of the repo.

=back

=head1 Repo Methods

Repo methods generally require an authorized session. The AT Protocol treats 'posts' and other data as records stored
in repositories.

=head2 C<applyWrites( ..., [...] )>

    $at->applyWrites( $at->did, [ ... ] );

Apply a batch transaction of creates, updates, and deletes.

Expected parameters include:

=over

=item C<repo> - required

The handle or DID of the repo.

=item C<writes>

Array of L<At::Lexicon::com::atproto::repo::applyWrites::create>,
L<At::Lexicon::com::atproto::repo::applyWrites::update>, or L<At::Lexicon::com::atproto::repo::applyWrites::delete>
objects.

=item C<validate> - required

Flag for validating the records.

=item C<swapCommit>

=back

Returns a true value on success.

=head2 C<createRecord( ..., [...] )>

Create a new record.

    $at->createRecord(
        $at->did,
        'app.bsky.feed.post',
        { '$type' => 'app.bsky.feed.post', text => "Hello world! I posted this via the API.", createdAt => gmtime->datetime . 'Z' }
    );

Expected parameters include:

=over

=item C<repo> - required

The handle or DID of the repo.

=item C<collection> - required

The NSID of the record collection.

=item C<record> - required

The record to create.

=item C<validate>

Flag for validating the record.

=item C<swapCommit>

Compare and swap with the previous commit by CID.

=item C<rkey>

The key of the record.

=back

Returns the uri and cid of the newly created record on success.

=head2 C<deleteRecord( ..., [...] )>

Create a new record.

    $at->deleteRecord( $at->did, 'app.bsky.feed.post', '3kiburrigys27' );

Expected parameters include:

=over

=item C<repo> - required

The handle or DID of the repo.

=item C<collection> - required

The NSID of the record collection.

=item C<rkey>

The key of the record.

=item C<swapRecord>

Compare and swap with the previous record by CID.

=item C<swapCommit>

Compare and swap with the previous commit by CID.

=back

Returns a true value on success.

=head2 C<describeRepo( ... )>

    $at->describeRepo( $at->did );

Get information about the repo, including the list of collections.

Expected parameters include:

=over

=item C<repo> - required

The handle or DID of the repo.

=back

On success, returns the repo's handle, did, a didDoc, a list of supported collections, a flag indicating whether or not
the handle is correct.










=head1 Admin Methods

These should only be called by a member of the server's administration team.

=head2 C<admin_deleteAccount( ... )>

    $at->admin_deleteAccount( 'did://...' );

Delete a user account as an administrator.

Expected parameters include:

=over

=item C<did> - required

=back

Returns a true value on success.

=head2 C<admin_disableAccountInvites( ..., [...] )>

    $at->admin_disableAccountInvites( 'did://...' );

Disable an account from receiving new invite codes, but does not invalidate existing codes.

Expected parameters include:

=over

=item C<account> - required

=item C<note>

Optional reason for disabled invites.

=back

Returns a true value on success.

=head2 C<admin_emitModerationEvent( ..., [...] )>

    $at->admin_emitModerationEvent( ... );

Take a moderation action on an actor.

Expected parameters include:

=over

=item C<event> - required

=item C<subject> - required

=item C<createdBy> - required

=item C<subjectBlobCids>

=back

Returns a new C<At::Lexicon::com::atproto::admin::modEventView> object on success.

=head2 C<admin_enableAccountInvites( ..., [...] )>

    $at->admin_enableAccountInvites( 'did://...' );

Re-enable an account's ability to receive invite codes.

Expected parameters include:

=over

=item C<account> - required

=item C<note>

Optional reason for enabled invites.

=back

Returns a true value on success.

=head2 C<admin_getAccountInfo( ..., [...] )>

    $at->admin_getAccountInfo( 'did://...' );

Get details about an account.

Expected parameters include:

=over

=item C<did> - required

=back

Returns a new C<At::Lexicon::com::atproto::admin::accountView> object on success.

=head2 C<admin_getInviteCodes( [...] )>

    $at->admin_getInviteCodes( );

Get an admin view of invite codes.

Expected parameters include:

=over

=item C<sort>

Order to sort the codes: 'recent' or 'usage' with 'recent' being the default.

=item C<limit>

How many codes to return. Minimum of 1, maximum of 500, default of 100.

=item C<cursor>

=back

Returns a new C<At::Lexicon::com::atproto::server::inviteCode> object on success.

=head2 C<admin_getModerationEvent( ... )>

    $at->admin_getModerationEvent( 77736393829 );

Get details about a moderation event.

Expected parameters include:

=over

=item C<id> - required

=back

Returns a new C<At::Lexicon::com::atproto::admin::modEventViewDetail> object on success.

=head2 C<admin_getRecord( ..., [...] )>

    $at->admin_getRecord( 'at://...' );

Get details about a record.

Expected parameters include:

=over

=item C<uri> - required

=item C<cid>

=back

Returns a new C<At::Lexicon::com::atproto::admin::recordViewDetail> object on success.

=head2 C<admin_getRepo( ... )>

    $at->admin_getRepo( 'did:...' );

Get details about a repository.

Expected parameters include:

=over

=item C<did> - required

=back

Returns a new C<At::Lexicon::com::atproto::admin::repoViewDetail> object on success.

=head2 C<admin_getSubjectStatus( [...] )>

    $at->admin_getSubjectStatus( 'did:...' );

Get details about a repository.

Expected parameters include:

=over

=item C<did>

=item C<uri>

=item C<blob>

=back

Returns a subject and, optionally, the takedown reason as a new C<At::Lexicon::com::atproto::admin::statusAttr> object
on success.

=head2 C<admin_queryModerationEvents( [...] )>

    $at->admin_queryModerationEvents( 'did:...' );

List moderation events related to a subject.

Expected parameters include:

=over

=item C<types>

The types of events (fully qualified string in the format of C<com.atproto.admin#modEvent...>) to filter by. If not
specified, all events are returned.

=item C<createdBy>

=item C<sortDirection>

Sort direction for the events. C<asc> or C<desc>. Defaults to descending order of created at timestamp.

=item C<subject>

=item C<includeAllUserRecords>

If true, events on all record types (posts, lists, profile etc.) owned by the did are returned.

=item C<limit>

Minimum is 1, maximum is 100, 50 is the default.

=item C<cursor>

=back

Returns a list of events as new C<At::Lexicon::com::atproto::admin::modEventView> objects on success.

=head2 C<admin_queryModerationStatuses( [...] )>

    $at->admin_queryModerationStatuses( 'did:...' );

List moderation events related to a subject.

Expected parameters include:

=over

=item C<subject>

=item C<comment>

Search subjects by keyword from comments.

=item C<reportedAfter>

Search subjects reported after a given timestamp.

=item C<reportedBefore>

Search subjects reported before a given timestamp.

=item C<reviewedAfter>

Search subjects reviewed after a given timestamp.

=item C<reviewedBefore>

Search subjects reviewed before a given timestamp.

=item C<includeMuted>

By default, we don't include muted subjects in the results. Set this to true to include them.

=item C<reviewState>

Specify when fetching subjects in a certain state.

=item C<ignoreSubjects>

=item C<lastReviewedBy>

Get all subject statuses that were reviewed by a specific moderator.

=item C<sortField>

C<lastReviewedAt> or C<lastReportedAt>, which is the default.

=item C<sortDirection>

C<asc> or C<desc>, which is the default.

=item C<takendown>

Get subjects that were taken down.

=item C<limit>

Minimum of 1, maximum is 100, the default is 50.

=item C<cursor>

=back

Returns a list of subject statuses as new C<At::Lexicon::com::atproto::admin::subjectStatusView> objects on success.

=head2 C<admin_searchRepos( [...] )>

    $at->admin_searchRepos( 'hydra' );

Find repositories based on a search term.

Expected parameters include:

=over

=item C<query>

=item C<limit>

Minimum of 1, maximum is 100, the default is 50.

=item C<cursor>

=back

Returns a list of repos as new C<At::Lexicon::com::atproto::admin::repoView> objects on success.

=head2 C<admin_sendEmail( ..., [...] )>

    $at->admin_sendEmail( 'did:...', 'Hi!', 'did:...' );

Send email to a user's account email address.

Expected parameters include:

=over

=item C<recipientDid> - required

=item C<senderDid> - required

=item C<content> - required

=item C<subject>

=item C<comment>

Additional comment by the sender that won't be used in the email itself but helpful to provide more context for
moderators/reviewers.

=back

Returns a sent status boolean.

=head2 C<admin_updateAccountEmail( ... )>

    $at->admin_updateAccountEmail( 'atproto2.bsky.social', 'contact@example.com' );

Administrative action to update an account's email.

Expected parameters include:

=over

=item C<account> - required

The handle or DID of the repo.

=item C<email> - required

=back

Returns a true value on success.

=head2 C<admin_updateAccountHandle( ... )>

    $at->admin_updateAccountHandle( 'did:...', 'atproto2.bsky.social' );

Administrative action to update an account's handle.

Expected parameters include:

=over

=item C<did> - required

=item C<handle> - required

=back

Returns a true value on success.

=head2 C<admin_updateSubjectStatus( ..., [...] )>

    $at->admin_updateSubjectStatus( ... );

Update the service-specific admin status of a subject (account, record, or blob).

Expected parameters include:

=over

=item C<subject> - required

=item C<takedown>

=back

Returns the subject and takedown objects on success.

=head1 Identity Methods

These methods allow you to quickly update or gather information about a repository.

=head2 C<resolveHandle( ... )>

    $at->resolveHandle( 'atproto.bsky.social' );

Provides the DID of a repo.

Expected parameters include:

=over

=item C<handle> - required

The handle to resolve.

=back

Returns the DID on success.

=head2 C<updateHandle( ... )>

    $at->updateHandle( 'atproto.bsky.social' );

Updates the handle of the account.

Expected parameters include:

=over

=item C<handle> - required

=back

Returns a true value on success.

=head1 Moderation Methods

These methods allow you to help moderate the content on the network.

=head2 C<createReport( ..., [...] )>

    $at->createReport( { '$type' => 'com.atproto.moderation.defs#reasonSpam' }, { '$type' => 'com.atproto.repo.strongRef', uri => ..., cid => ... } );

Report a repo or a record.

Expected parameters include:

=over

=item C<reasonType> - required

An C<At::Lexicon::com::atproto::moderation::reasonType> object.

=item C<subject> - required

An C<At::Lexicon::com::atproto::admin::repoRef> or C<At::Lexicon::com::atproto::repo::strongRef> object.

=item C<reason>

=back

On success, an id, the original reason type, subject, and reason, are returned as well as the DID of the user making
the report and a timestamp.

=head1 Server Methods

Server methods may require an authorized session.

=head2 C<createSession( ... )>

    $at->createSession( 'sanko', '1111-2222-3333-4444' );

Create an authentication session.

Expected parameters include:

=over

=item C<identifier> - required

Handle or other identifier supported by the server for the authenticating user.

=item C<password> - required

=back

On success, the access and refresh JSON web tokens, the account's handle, DID and (optionally) other data is returned.

=head2 C<describeServer( )>

Get a document describing the service's accounts configuration.

    $at->describeServer( );

This method does not require an authenticated session.

Returns a boolean value indicating whether an invite code is required, a list of available user domains, and links to
the TOS and privacy policy.

=head2 C<listAppPasswords( )>

    $at->listAppPasswords( );

List all App Passwords.

Returns a list of passwords as new C<At::Lexicon::com::atproto::server::listAppPasswords::appPassword> objects.

=head2 C<getSession( )>

    $at->getSession( );

Get information about the current session.

Returns the handle, DID, and (optionally) other data.

=head2 C<getAccountInviteCodes( )>

    $at->getAccountInviteCodes( );

Get all invite codes for a given account.

Returns codes as a list of new C<At::Lexicon::com::atproto::server::inviteCode> objects.

=head2 C<getAccountInviteCodes( [...] )>

    $at->getAccountInviteCodes( );

Get all invite codes for a given account.

Expected parameters include:

=over

=item C<includeUsed>

Optional boolean flag.

=item C<createAvailable>

Optional boolean flag.

=back

Returns a list of C<At::Lexicon::com::atproto::server::inviteCode> objects on success. Note that this method returns an
error if the session was authorized with an app password.

=head2 C<updateEmail( ..., [...] )>

    $at->updateEmail( 'smith...@gmail.com' );

Update an account's email.

Expected parameters include:

=over

=item C<email> - required

=item C<token>

This method requires a token from C<requestEmailUpdate( ... )> if the account's email has been confirmed.

=back

=head2 C<requestEmailUpdate( ... )>

    $at->requestEmailUpdate( 1 );

Request a token in order to update email.

Expected parameters include:

=over

=item C<tokenRequired> - required

Boolean value.

=back

=head2 C<revokeAppPassword( ... )>

    $at->revokeAppPassword( 'Demo App [beta]' );

Revoke an App Password by name.

Expected parameters include:

=over

=item C<name> - required

=back

=head2 C<resetPassword( ... )>

    $at->resetPassword( 'fdsjlkJIofdsaf89w3jqirfu2q8docwe', '****************' );

Reset a user account password using a token.

Expected parameters include:

=over

=item C<token> - required

=item C<password> - required

=back

=head2 C<resetPassword( ... )>

    $at->resetPassword( 'fdsjlkJIofdsaf89w3jqirfu2q8docwe', '****************' );

Reset a user account password using a token.

Expected parameters include:

=over

=item C<token> - required

=item C<password> - required

=back

=head2 C<reserveSigningKey( [...] )>

    $at->reserveSigningKey( 'did:...' );

Reserve a repo signing key for account creation.

Expected parameters include:

=over

=item C<did>

The did to reserve a new did:key for.

=back

On success, a public signing key in the form of a did:key is returned.

=head2 C<requestPasswordReset( [...] )>

    $at->requestPasswordReset( 'smith...@gmail.com' );

Initiate a user account password reset via email.

Expected parameters include:

=over

=item C<email> - required

=back

=head2 C<requestEmailConfirmation( )>

    $at->requestEmailConfirmation( );

Request an email with a code to confirm ownership of email.

=head2 C<requestAccountDelete( )>

    $at->requestAccountDelete( );

Initiate a user account deletion via email.

=head2 C<deleteSession( )>

    $at->deleteSession( );

Initiate a user account deletion via email.

=head2 C<deleteAccount( )>

    $at->deleteAccount( );

Delete an actor's account with a token and password.

Expected parameters include:

=over

=item C<did> - required

=item C<password> - required

=item C<token> - required

=back

=head2 C<createInviteCodes( ..., [...] )>

    $at->createInviteCodes( 1, 1 );

Create invite codes.

Expected parameters include:

=over

=item C<codeCount> - required

The number of codes to create. Default value is 1.

=item C<useCount> - required

Int.

=item C<forAccounts>

List of DIDs.

=back

On success, returns a list of new C<At::Lexicon::com::atproto::server::createInviteCodes::accountCodes> objects.

=head2 C<createInviteCode( ..., [...] )>

    $at->createInviteCode( 1 );

Create an invite code.

Expected parameters include:

=over

=item C<useCount> - required

Int.

=item C<forAccounts>

List of DIDs.

=back

On success, a new invite code is returned.

=head2 C<createAppPassword( ..., [...] )>

    $at->createAppPassword( 'AT Client [release]' );

Create an App Password.

Expected parameters include:

=over

=item C<name> - required

=back

On success, a new C<At::Lexicon::com::atproto::server::createAppPassword::appPassword> object.

=head2 C<createAccount( ..., [...] )>

    $at->createAccount( 'jsmith....', '*********' );

Create an account.

Expected parameters include:

=over

=item C<handle> - required

=item C<email>

=item C<password>

=item C<inviteCode>

=item C<did>

=item C<recoveryKey>

=item C<plcOP>

=back

On success, JSON web access and refresh tokens, the handle, did, and (optionally) a server defined didDoc are returned.

=head2 C<confirmEmail( ... )>

    $at->confirmEmail( 'jsmith...@gmail.com', 'idkidkidkidkdifkasjkdfsaojfd' );

Confirm an email using a token from C<requestEmailConfirmation( )>,

Expected parameters include:

=over

=item C<email> - required

=item C<token> - required

=back

=begin todo

=head1 Label Methods

Lables are metadata tags on an atproto resource (eg, repo or record).

=head2 C<queryLabels( ... )>

    $at->queryLabels( '' );

Find labels relevant to the provided URI patterns.

Expected parameters include:

=over

=item C<uriPatterns> - required

List of AT URI patterns to match (boolean 'OR'). Each may be a prefix (ending with '*'; will match inclusive of the
string leading to '*'), or a full URI.

=item C<sources>

Optional list of label sources (DIDs) to filter on.

=item C<limit>

Number of results to return. 250 max. Default is 50.

=item C<cursor>

=back

On success, labels are returned as a list of new C<At::Lexicon::com::atproto::label> objects.

=head2 C<subscribeLabels( ..., [...] )>

    $at->subscribeLabels( sub { ... } );

Subscribe to label updates.

Expected parameters include:

=over

=item C<callback> - required

Code reference triggered with every event.

=item C<cursor>

The last known event to backfill from.

=back

On success, a websocket is initiated. Events we recieve include
C<At::Lexicon::com::atproto::label::subscribeLables::labels> and
C<At::Lexicon::com::atproto::label::subscribeLables::info> objects.

=head2 C<subscribeLabels_p( ..., [...] )>

    $at->subscribeLabels_p( sub { ... } );

Subscribe to label updates.

Expected parameters include:

=over

=item C<callback> - required

Code reference triggered with every event.

=item C<cursor>

The last known event to backfill from.

=back

On success, a websocket is initiated and a promise is returned. Events we recieve include
C<At::Lexicon::com::atproto::label::subscribeLables::labels> and
C<At::Lexicon::com::atproto::label::subscribeLables::info> objects.

=head1 Services

Currently, there are 3 sandbox At Protocol services:

=over

=item PLC

    my $at = At->new( host => 'plc.bsky-sandbox.dev' );

This is the default DID provider for the network. DIDs are the root of your identity in the network. Sandbox PLC
functions exactly the same as production PLC, but it is run as a separate service with a separate dataset. The DID
resolution client in the self-hosted PDS package is set up to talk the correct PLC service.

=item BGS

    my $at = At->new( host => 'bgs.bsky-sandbox.dev' );

BGS (Big Graph Service) is the firehose for the entire network. It collates data from PDSs & rebroadcasts them out on
one giant websocket.

BGS has to find out about your server somehow, so when we do any sort of write, we ping BGS with
com.atproto.sync.requestCrawl to notify it of new data. This is done automatically in the self-hosted PDS package.

If you’re familiar with the Bluesky production firehose, you can subscribe to the BGS firehose in the exact same
manner, the interface & data should be identical

=item BlueSky Sandbox

    my $at = At->new( host => 'api.bsky-sandbox.dev' );

The Bluesky App View aggregates data from across the network to service the Bluesky microblogging application. It
consumes the firehose from the BGS, processing it into serviceable views of the network such as feeds, post threads,
and user profiles. It functions as a fairly traditional web service.

When you request a Bluesky-related view from your PDS (getProfile for instance), your PDS will actually proxy the
request up to App View.

Feel free to experiment with running your own App View if you like!

=back

You may also configure your own personal data server (PDS).

    my $at = At->new( host => 'your.own.com' );

PDS (Personal Data Server) is where users host their social data such as posts, profiles, likes, and follows. The goal
of the sandbox is to federate many PDS together, so we hope you’ll run your own.

We’re not actually running a Bluesky PDS in sandbox. You might see Bluesky team members' accounts in the sandbox
environment, but those are self-hosted too.

The PDS that you’ll be running is much of the same code that is running on the Bluesky production PDS. Notably, all
of the in-pds-appview code has been torn out. You can see the actual PDS code that you’re running on the
atproto/simplify-pds branch.

=end todo

=head1 See Also

L<https://atproto.com/>

L<Bluesky on Wikipedia.org|https://en.wikipedia.org/wiki/Bluesky_(social_network)>

=head1 LICENSE

Copyright (C) Sanko Robinson.

This library is free software; you can redistribute it and/or modify it under the terms found in the Artistic License
2. Other copyrights, terms, and conditions may apply to data transmitted through this module.

=head1 AUTHOR

Sanko Robinson E<lt>sanko@cpan.orgE<gt>

=begin stopwords

didDoc cids cid

=end stopwords

=cut
